version: '3.6'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            - ELASTICSEARCH_URLS=http://elasticsearch:9200
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:7.8.0
        ports:
            - 5601:5601
